Refactoring and async improvement
Liestro/eodhd pull request #1
Opened 2024-09-17 15:45 UTC by Liestro

2024-09-18 08:49 UTC, aisurfer requested changes

2024-09-18 08:49 UTC, aisurfer commented on TODO
> +1. **Обработка ошибок и исключений**: Добавить обработку исключений в `main.py` и `async_eodhd_api.py` для управления сбоями HTTP-запросов и операций с базой данных.
это точно нужно

2024-09-18 08:49 UTC, aisurfer commented on TODO
> +2. **Логирование**: Реализовать систему логирования вместо использования `print()` для улучшения отладки и мониторинга работы приложения.
принты ок, мы копим логи docker и этого хватает пока

2024-09-18 08:49 UTC, aisurfer commented on TODO
> +3. **Конфигурация**: Переместить жестко закодированные параметры (URL API, периоды данных) в конфигурационный файл или переменные окружения.
сделаем когда внесем код в датасторадж, там есть уже нужные механизмы

2024-09-18 08:49 UTC, aisurfer commented on TODO
> +4. **Безопасность**: Удалить все оставшиеся закомментированные API-ключи и пароли, обеспечить безопасное хранение ключей.
тоже

2024-09-18 08:49 UTC, aisurfer commented on TODO
> +5. **Документация**: Добавить докстринги для всех классов и функций для улучшения понимания кода.
можно забить, и так понятно

2024-09-18 08:49 UTC, aisurfer commented on TODO
> +6. **Тестирование**: Написать модульные тесты для проверки корректности работы отдельных компонентов проекта.
это нужно

2024-09-18 08:49 UTC, aisurfer commented on TODO
> +9. **Управление соединениями**: Внедрить пул соединений для MongoDB, чтобы избежать создания соединения для каждой операции.
нужно

2024-09-18 08:49 UTC, aisurfer commented on TODO
> +12. **Типизация**: Добавить аннотации типов Python для улучшения читаемости и обнаружения ошибок в коде.
пока не нужно

2024-09-18 08:49 UTC, aisurfer commented on async_eodhd_api.py
> +class EodhdAPISession:
этот класс выглядит ок

2024-09-18 08:49 UTC, aisurfer commented on async_eodhd_api.py
> +if __name__ == '__main__':
лучше отдельно модуль с классом и отдельно test_...py в котором можно мейн написать или тесты

2024-09-18 08:49 UTC, aisurfer commented on db_operations.py
> +    mongo_client.eodhd.fundamentals_data.create_index([("name", pymongo.ASCENDING)], unique=True)
индекс пересоздается на каждый вызов. Раздели на две функции, чтобы сначала записать данные, а потом один раз вызвать create_index

2024-09-18 08:49 UTC, aisurfer commented on db_operations.py
> +    if not mongo_client.eodhd.fundamentals_data.count_documents({"name": fundamental_data["name"]}):
вот тут не понял. А что если нужно перезаписать данные? Например заново скачали и нужно обновить?
если это защита от повторной записи при повторном запуске программы, сделай флажок в параметре функции и аргумент при запуске программы. Который будет значить "это просто повторный запуск, не перезаписывай всё".
По умолчанию - перезаписывать всё заново

2024-09-18 08:49 UTC, aisurfer commented on main.py
> +
вот это не очень. Сначала всё собираешь в память и только потом всё записываешь.
Переделай на 
- скачал по очередному тикеру
- сразу записал

2024-09-18 08:49 UTC, aisurfer commented on main.py
> +        fundamental_data_tasks = [session.get_fundamental_data(symbol) for symbol in symbols]
надо добавить обработку исключений, 500к и ретраи. Что если на 999м из 1000 ошибка и программа падает?
Что если один из http вызовов вернул временный неответ (в апихах такое часто бывает)

2024-09-18 08:49 UTC, aisurfer commented on main.py
> +                mongo_client.fundamental_data[symbol].replace_one({}, data, upsert=True)
заноси всё это в db_opreations.py

2024-09-18 09:26 UTC, Liestro commented on db_operations.py
> +    mongo_client.eodhd.fundamentals_data.create_index([("name", pymongo.ASCENDING)], unique=True)
Этот метод нигде не испоьзуется. Забытый пережиток прошлого. Я его удалю

2024-09-18 09:27 UTC, Liestro commented on main.py
> +
Тоже посетила такая мысль чуть позже

2024-09-23 20:23 UTC, aisurfer approved these changes
всё выглядит ок, давай мерджить

2024-09-23 20:26 UTC, merged